# Generated by Django 4.1.13 on 2023-11-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emptycuptask', '0002_alter_designinstitutions_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignInstitutions',
            new_name='DesignInstitution',
        ),
    ]
