# Generated by Django 4.1.13 on 2023-11-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptycuptask', '0003_rename_designinstitutions_designinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='designinstitution',
            name='no_of_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
